### ISSUE TITLE
rethink about clientside verification

### ISSUE THREAD

**Issue by slayerpart** [HPI-DeepLearning/CaptchaService#5]

**Comment by Bartzi** [comment]
please have a look at the Recaptcha Documentation:
https://developers.google.com/recaptcha/docs/verify

What they are doing is exactly we thing mentioned during your presentation.
1. the user comes to the site and loads a Recaptcha iframe from the captcha service, he thereby also provides an API key of the webapp that he visits (I do not think that we need to have this API key in our database, if we go for the same solution)
2. the captcha service creates a session for the user an sends the challenge including a one-time token, that will be verified later
3. the client solves the captcha and lets recpatcha verify his solution, recaptcha then returns a success response and shows it to the user
4. the user submits his form to the webapp, this form now includes the one-time token provided by recaptcha 
5. the webapp sends a request to the captcha service, including the api-key and the one-time token, if the token has not been verified by the webapp before the service returns a success response, otherwise a reject response and the client has to solve a captcha again (google actually also uses a secret key, I actually do not really see the benefit, other than that it might be possible to mitigate possible DoS attacks on the web-app)

You can also have a look at some official reCaptcha Demos:
https://www.google.com/recaptcha/demo/
https://www.google.com/recaptcha/api2/demo

So I would suggest that we try to implement our verification in the same way. I'm not 100% sure whether we really need a fixed API-Key, because this is only used to make sure that the webservice asks for the solution of a captcha that he wanted the client to solve...

I hope this helps and it is somehow clear what I want to tell you^^
